[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
libs = ["contracts/lib"]
remappings = [
    "@uniswap/v4-core/=contracts/lib/v4-core/",
    "@uniswap/v4-core/src/=contracts/lib/v4-core/src/",
    "forge-std/=contracts/lib/v4-core/lib/forge-std/src/",
    "solmate/=contracts/lib/v4-core/lib/solmate/src/",
    "@openzeppelin/=contracts/lib/v4-core/lib/openzeppelin-contracts/"
]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
